<?php

namespace MertOksuz\ApiBundle\Repository;

/**
 * DenemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DenemeRepository extends \Doctrine\ORM\EntityRepository
{
}
